name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull latest code and restart app
        run: |
          cd /home/uabc/ISEP-PESTI/planetpulse-next
          git pull
          sudo systemctl restart planetpulse.service
